### ISSUE TITLE
Ajuda com o banco de dados

### ISSUE THREAD

**Issue by terolando** [leguass7/n2bt-next#3]
Primeiramente parabéns pelo projeto. Dei uma olhadinha e gostei muito. Acho q me serviria demais pro que estou querendo fazer.
Mas estou com algumas duvidas: 
Executo o npm install e depois o npm run dev. Até aqui tudo bem. Ele sobe o servidor, porém da erro de conexão com o banco nos logs.
Eu tenho q instalar o banco manualmente por fora ou era pro próprio sistema ja instalar? Existe algum arquivo pra configurar essa conexão ou até mesmo criação do banco, ou somente o .env q tenho que criar? E qual a versão do node vc usa nele?

**Comment by severoemanuel** [comment]
Obrigado @terolando, quanto ao banco de dados. Essa estrutura em específico tem um script chamando "sync" no package.json. você roda yarn sync ou npm run sync e ele cria as tabelas no seu banco de dados

**Comment by terolando** [comment]
Fiz aqui. E a pagina rodou direitinho. Fiz o cadastro de um usuário tudo certinho também. 
Existe algum usuário administrador? Onde eu crio os torneios? O arquivo para configurar um smtp para envio de email é o smtp.provider.ts ?
Me desculpa a quantidade de perguntas.

**Comment by terolando** [comment]
@severoemanuel

**Comment by terolando** [comment]
Funcionou!!
