### ISSUE TITLE
Bug ao adicionar imagem ao torneio.

### ISSUE THREAD

**Issue by terolando** [leguass7/n2bt-next#5]
Sempre que adiciono uma imagem ao torneio, ele só aparece na tela principal quando o usuário está inscrito no torneio. Fora isso aparece uma imagem aleatória que fica em .next/static/media. E esmo inscrito no torneio, quando entro em minhas inscrições a imagem também é outra.

**Comment by leguass7** [comment]
Estou fazendo essa correção. Não estou fazendo a melhor abordagem obtendo a imagem através do fetch, porém funciona de imediato.
Uma outra abordagem interessante nesse cenário, seria adquirir o `src` da imagem no `getServerSideProps`, assim daria para aproveitar minimamante o cache do nextJs.
